package com.dipdv.shared.audit;

public enum AuditAction {
    ORDER_CANCELED,
    ORDER_CLOSED,
    ORDER_ITEM_QUANTITY_UPDATED,
    CASH_REGISTER_OPENED,
    CASH_REGISTER_CLOSED,
    STOCK_ADJUSTED,
    PRODUCT_DELETED,
    USER_CREATED,
    USER_UPDATED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    PAYMENT_REGISTERED,
    PAYMENT_REFUNDED,

    // Ações SUPER_ADMIN
    SUPER_ADMIN_TENANT_CREATED,
    SUPER_ADMIN_TENANT_DEACTIVATED,
    SUPER_ADMIN_TENANT_UPDATED,
    SUPER_ADMIN_DATA_ACCESS,
    SUPER_ADMIN_LOGIN
}